### ISSUE TITLE
Publish gem on Rubygems.org

### ISSUE THREAD

**Issue by doc75** [tjwallace/fit#12]
I might be a good idea to publish this gem on Rubygems.org.
I can see that somebody published this gem as garmin-fit (cf: https://rubygems.org/gems/garmin-fit), and the name fit is already used for something else.
Would that be a good idea to find a proper name (I would say without Garmin to avoid intellectual property issue) and publish it ?

I was thinking to names like:
  - fity
  - fityn (fit + end of garmin)

Sorry I am probably not so good at finding names.
Any ideas ?

**Comment by andrewwu** [comment]
How does fit-sdk sound?

**Comment by doc75** [comment]
To my view, this is not really a SDK but more a fit-parser.
SDK might be confusing as tthere is an official Fit SDk (not in Ruby) published by Ant+.

Actually while answering you I noticed that somebody published less than a month ago a version of this code here: https://rubygems.org/gems/fit_parser/ and it comes from: https://github.com/zhublik/fit_parser (but this is not a fork of the main repository).

I do not know how we can reconciliate that for now.

**Comment by tjwallace** [comment]
How about fit-file?

**Comment by andrewwu** [comment]
Ah, yes I agree with the fit-sdk argument.

I do like fit-ruby, kind of like https://github.com/stripe/stripe-ruby or since fit_parser is taken we could go with fit-parser.

**Comment by doc75** [comment]
I would rather avoid confusion between fit_parser and fit-parser.
After some extra research fit-parser is also taken here: https://github.com/duereg/fit-parser ;-(

fit-file or fit-ruby would be fine for me.

**Comment by andrewwu** [comment]
@doc75 I think fit-parser is fine to use because:

* fit_parser is an "illegitimate" fork of this repository (3 commits, same codebase) that was published unofficially to RubyGems (I believe it would have been a courtesy to first ask @tjwallace if he could publish this library as a gem rather than duplicating the repo and publishing it himself[1])
* fit-parser doesn't look like it's taken on RubyGems
* the fit-parser you linked is a NPM package that has no relationship with Garmin fit files at all

[1] I could be wrong, all of these authors publishing unofficial versions of this library on RubyGems may have asked for permission first.

**Comment by doc75** [comment]
You are right for the NPM package. Sorry for the confusion.

**Comment by tjwallace** [comment]
`fit-parser` works for me

**Comment by tjwallace** [comment]
Although `fit-parser` doesn't follow [the naming conventions](http://guides.rubygems.org/name-your-gem/)

**Comment by andrewwu** [comment]
@tjwallace I think that's fine. We can just name the gem fit-parser but keep the classes and modules as-is.

**Comment by tjwallace** [comment]
Deployed to RubyGems.org as [`fit-parser`](https://rubygems.org/gems/fit-parser). Thanks to all for your help!
